site_name: HyperiumJailbreak

theme:
  name: 'material'
  logo: 'assets/logo.png'
  favicon: 'favicon.ico'
  palette:
    primary: 'blue'
    accent: 'indigo'

repo_name: 'hyperiumjailbreak/website'
repo_url: 'https://github.com/hyperiumjailbreak/website'
edit_uri: 'blob/master/docs/'

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

site_description: Jailbroken Hyperium client.
site_url: https://hyperiumjailbreak.com
site_author: HyperiumJailbreak Team
copyright: Copyright (©) HyperiumJailbreak Team 2019-present | Not affiliated with Mojang AB.
remote_branch: master

extra:
  manifest: 'manifest.json'
  social:
    - type: 'github'
      link: 'https://github.com/hyperiumjailbreak'

nav:
  - 'Home': index.md
  - 'Features': features.md
  - 'Installing': installation.md
  - 'Addons': addons.md
  - 'FAQ / Help Center': faq.md
  - 'Our Sponsor': cloudrepo.md
  - 'Changelog': changelog.md
  - 'Privacy Policy': privacy.md
  - 'Contributing':
    - 'Development Guide': contrib/development.md
    - 'Code of Conduct': contrib/CODE_OF_CONDUCT.md
    - 'Pull Request Policy': contrib/pr_policy.md
  - 'About':
    - 'Mission': about/mission.md
    - 'Statistics': about/stats.md
